export const AppErrorCode = {
  AUTH_REQUIRED: 'AUTH.REQUIRED',
  CURRENT_USER_NOT_FOUND: 'AUTH.CURRENT_USER_NOT_FOUND',
  INVALID_CREDENTIALS: 'AUTH.INVALID_CREDENTIALS',
  USER_DEACTIVATED: 'AUTH.USER_DEACTIVATED',

  USER_NOT_FOUND: 'USER.NOT_FOUND',
  USER_USERNAME_ALREADY_EXISTS: 'USER.USERNAME_ALREADY_EXISTS',
  USER_STAFF_ID_ALREADY_EXISTS: 'USER.STAFF_ID_ALREADY_EXISTS',

  ROLE_NOT_FOUND: 'ROLE.NOT_FOUND',
  ROLE_NAME_ALREADY_EXISTS: 'ROLE.NAME_ALREADY_EXISTS',

  PERMISSION_NOT_FOUND: 'PERMISSION.NOT_FOUND',
  PERMISSION_NAME_ALREADY_EXISTS: 'PERMISSION.NAME_ALREADY_EXISTS',

  ORDERING_IDS_INVALID: 'ORDERING.IDS_INVALID',
  ORDERING_COLLECTION_MISMATCH: 'ORDERING.COLLECTION_MISMATCH',

  FACILITY_NOT_FOUND: 'FACILITY.NOT_FOUND',
  FACILITY_SLUG_ALREADY_EXISTS: 'FACILITY.SLUG_ALREADY_EXISTS',

  SERVICE_NOT_FOUND: 'SERVICE.NOT_FOUND',
  SERVICE_SLUG_ALREADY_EXISTS: 'SERVICE.SLUG_ALREADY_EXISTS',
  SERVICE_VARIANT_NOT_FOUND: 'SERVICE_VARIANT.NOT_FOUND',
  SERVICE_VARIANT_SLUG_ALREADY_EXISTS: 'SERVICE_VARIANT.SLUG_ALREADY_EXISTS',
  SERVICE_VARIANT_CLUB_NOT_IN_SERVICE: 'SERVICE_VARIANT.CLUB_NOT_IN_SERVICE',

  CLUB_NOT_FOUND: 'CLUB.NOT_FOUND',
  CLUB_SLUG_ALREADY_EXISTS: 'CLUB.SLUG_ALREADY_EXISTS',
  CLUB_GALLERY_ORDER_INVALID: 'CLUB.GALLERY_ORDER_INVALID',

  MEMBERSHIP_LEVEL_NOT_FOUND: 'MEMBERSHIP_LEVEL.NOT_FOUND',
  MEMBERSHIP_LEVEL_SLUG_ALREADY_EXISTS: 'MEMBERSHIP_LEVEL.SLUG_ALREADY_EXISTS',

  MEMBERSHIP_BENEFIT_NOT_FOUND: 'MEMBERSHIP_BENEFIT.NOT_FOUND',

  MEMBERSHIP_PLAN_NOT_FOUND: 'MEMBERSHIP_PLAN.NOT_FOUND',
  MEMBERSHIP_PLAN_ALREADY_EXISTS: 'MEMBERSHIP_PLAN.ALREADY_EXISTS',

  BANNER_NOT_FOUND: 'BANNER.NOT_FOUND',
  BANNER_INVALID_DATE_RANGE: 'BANNER.INVALID_DATE_RANGE',

  CUSTOMER_LEAD_NOT_FOUND: 'CUSTOMER_LEAD.NOT_FOUND',
  CUSTOMER_LEAD_CONSENT_REQUIRED: 'CUSTOMER_LEAD.CONSENT_REQUIRED',

  CONTACT_NOT_FOUND: 'CONTACT.NOT_FOUND',

  MEDIA_ASSET_NOT_FOUND: 'MEDIA_ASSET.NOT_FOUND',
  MEDIA_ASSET_NOT_IMAGE: 'MEDIA_ASSET.NOT_IMAGE',
  MEDIA_ASSET_INACTIVE: 'MEDIA_ASSET.INACTIVE',
  MEDIA_ASSET_IN_USE: 'MEDIA_ASSET.IN_USE',
  MEDIA_ASSET_FILE_REQUIRED: 'MEDIA_ASSET.FILE_REQUIRED',
  MEDIA_ASSET_FILE_TOO_LARGE: 'MEDIA_ASSET.FILE_TOO_LARGE',
  MEDIA_ASSET_UNSUPPORTED_IMAGE_TYPE: 'MEDIA_ASSET.UNSUPPORTED_IMAGE_TYPE',
  MEDIA_ASSET_INVALID_IMAGE: 'MEDIA_ASSET.INVALID_IMAGE',
  MEDIA_ASSET_MIME_MISMATCH: 'MEDIA_ASSET.MIME_MISMATCH',
  MEDIA_ASSET_MANAGED_FILE_IMMUTABLE: 'MEDIA_ASSET.MANAGED_FILE_IMMUTABLE',
  MEDIA_ASSET_INVALID_CROP_RECTANGLE: 'MEDIA_ASSET.INVALID_CROP_RECTANGLE',
  MEDIA_ASSET_CROP_OUT_OF_BOUNDS: 'MEDIA_ASSET.CROP_OUT_OF_BOUNDS',
  MEDIA_ASSET_CROP_UNSUPPORTED_IMAGE_TYPE:
    'MEDIA_ASSET.CROP_UNSUPPORTED_IMAGE_TYPE',
  MEDIA_ASSET_ORIGINAL_UNAVAILABLE: 'MEDIA_ASSET.ORIGINAL_UNAVAILABLE',
  MEDIA_ASSET_UNMANAGED_OR_EXTERNAL: 'MEDIA_ASSET.UNMANAGED_OR_EXTERNAL',
  MEDIA_ASSET_IMAGE_PROCESSING_FAILED: 'MEDIA_ASSET.IMAGE_PROCESSING_FAILED',
  MEDIA_ASSET_ORIGINAL_STORAGE_RETRIEVAL_FAILED:
    'MEDIA_ASSET.ORIGINAL_STORAGE_RETRIEVAL_FAILED',

  SITE_SETTING_NOT_FOUND: 'SITE_SETTING.NOT_FOUND',
  SITE_SETTING_KEY_ALREADY_EXISTS: 'SITE_SETTING.KEY_ALREADY_EXISTS',
  SITE_SETTING_NOT_EDITABLE: 'SITE_SETTING.NOT_EDITABLE',
  SITE_SETTING_INVALID_VALUE: 'SITE_SETTING.INVALID_VALUE',

  POST_CATEGORY_NOT_FOUND: 'POST_CATEGORY.NOT_FOUND',
  POST_CATEGORY_SLUG_ALREADY_EXISTS: 'POST_CATEGORY.SLUG_ALREADY_EXISTS',
  POST_CATEGORY_IN_USE: 'POST_CATEGORY.IN_USE',

  POST_NOT_FOUND: 'POST.NOT_FOUND',
  POST_SLUG_ALREADY_EXISTS: 'POST.SLUG_ALREADY_EXISTS',
  POST_CONTENT_TOO_LARGE: 'POST.CONTENT_TOO_LARGE',
  POST_INLINE_MEDIA_MARKER_INVALID: 'POST.INLINE_MEDIA_MARKER_INVALID',
} as const;

export type AppErrorCode = (typeof AppErrorCode)[keyof typeof AppErrorCode];
