export const AppErrorCode = {
  AUTH_REQUIRED: 'AUTH.REQUIRED',
  CURRENT_USER_NOT_FOUND: 'AUTH.CURRENT_USER_NOT_FOUND',
  INVALID_CREDENTIALS: 'AUTH.INVALID_CREDENTIALS',
  USER_DEACTIVATED: 'AUTH.USER_DEACTIVATED',

  USER_NOT_FOUND: 'USER.NOT_FOUND',
  USER_USERNAME_ALREADY_EXISTS: 'USER.USERNAME_ALREADY_EXISTS',
  USER_STAFF_ID_ALREADY_EXISTS: 'USER.STAFF_ID_ALREADY_EXISTS',

  ROLE_NOT_FOUND: 'ROLE.NOT_FOUND',
  ROLE_NAME_ALREADY_EXISTS: 'ROLE.NAME_ALREADY_EXISTS',

  PERMISSION_NOT_FOUND: 'PERMISSION.NOT_FOUND',
  PERMISSION_NAME_ALREADY_EXISTS: 'PERMISSION.NAME_ALREADY_EXISTS',
} as const;

export type AppErrorCode = (typeof AppErrorCode)[keyof typeof AppErrorCode];
